export const sampleSummary = {
  goal: 5000,
  raised: 3420,
  donorCount: 185,
  progressPercent: 68,
  pagination: {
    page: 1,
    pageSize: 30,
    total: 10,
    totalPages: 1,
    start: 1,
    end: 10,
  },
  milestones: [
    {
      label: "$1,250",
      amount: 1250,
      reached: true,
    },
    {
      label: "$2,500",
      amount: 2500,
      reached: true,
    },
    {
      label: "$3,750",
      amount: 3750,
      reached: false,
    },
    {
      label: "$5,000",
      amount: 5000,
      reached: false,
    },
  ],
  mediaGallery: [
    {
      title: "5K",
      type: "image",
      src: "assets/5k_Donacion_Junelly.PNG",
      alt: "Arte promocional del 5K Abrazo Solidario para Junelly",
    },
    {
      title: "Hoy Día",
      type: "image",
      src: "assets/Hoy_Dia_Telemundo_junelly.png",
      alt: "Participación de Junelly en Hoy Día Telemundo",
    },
    {
      title: "Junelly",
      type: "image",
      src: "assets/Junelly1.png",
      alt: "Foto de Junelly",
    },
    {
      title: "PR En Vivo",
      type: "image",
      src: "assets/PR_EN_VIVO_TELE_11_Junelly.png",
      alt: "Participación de Junelly en PR En Vivo",
    },
  ],
  donations: [
    {
      name: "Donante anónimo",
      amount: 10,
      message: "Bendiciones para Junelly.",
      date: "Hoy",
      anonymous: true,
    },
    {
      name: "María R.",
      amount: 20,
      message: "Con mucho cariño y apoyo.",
      date: "Hoy",
      anonymous: false,
    },
    {
      name: "Familia González",
      amount: 50,
      message: "Estamos contigo.",
      date: "Ayer",
      anonymous: false,
    },
    {
      name: "José P.",
      amount: 10,
      message: "Dios te bendiga.",
      date: "Ayer",
      anonymous: false,
    },
    {
      name: "Aixa T.",
      amount: 10,
      message: "Mucho éxito en el evento.",
      date: "2 días",
      anonymous: false,
    },
    {
      name: "Donante anónimo",
      amount: 25,
      message: "Un abrazo solidario.",
      date: "2 días",
      anonymous: true,
    },
    {
      name: "VIP Runner",
      amount: 30,
      message: "Nos vemos en el 5K.",
      date: "3 días",
      anonymous: false,
    },
    {
      name: "Amiga de carreras",
      amount: 100,
      message: "Seguimos apoyando con fe.",
      date: "3 días",
      anonymous: false,
    },
    {
      name: "Donante anónimo",
      amount: 15,
      message: "",
      date: "4 días",
      anonymous: true,
    },
    {
      name: "Equipo Solidario",
      amount: 75,
      message: "Toda la fuerza para este proceso.",
      date: "4 días",
      anonymous: false,
    },
  ],
};
